{{- if .Values.adminWeb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: forge-admin-web
  namespace: {{ .Values.adminNamespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    {{- include "forge.adminWeb.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.adminWeb.service.type }}
  ports:
    - port: {{ .Values.adminWeb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forge.adminWeb.selectorLabels" . | nindent 4 }}
{{- end }}
