{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: forge-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    {{- include "forge.web.selectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "forge.web.selectorLabels" . | nindent 4 }}
{{- end }}
