{{- if .Values.forgeWeb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forge-web
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "forge.labels" . | nindent 4 }}
    {{- include "forge.forgeWeb.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.forgeWeb.replicaCount }}
  selector:
    matchLabels:
      {{- include "forge.forgeWeb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "forge.forgeWeb.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web
          image: "{{ .Values.forgeWeb.image.repository }}:{{ .Values.forgeWeb.image.tag }}"
          imagePullPolicy: {{ .Values.forgeWeb.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.forgeWeb.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.forgeWeb.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.forgeWeb.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.forgeWeb.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.forgeWeb.resources | nindent 12 }}
{{- end }}
