import { Router } from "express";
import { db } from "../db/client";
import { teamRequests, teamTasks, agents } from "../db/schema";
import { eq } from "drizzle-orm";
import { authMiddleware } from "../middleware/authMiddleware";
import { z } from "zod";
import { logActivity } from "../lib/activity-logger";

export const requestsRouter = Router({ mergeParams: true });

const requestSchema = z.object({
  requesterId: z.string().uuid(),
  requesterType: z.enum(["human", "agent"]),
  targetAgentId: z.string().uuid(),
  teamTaskId: z.string().uuid().optional().nullable(),
  projectIssueId: z.string().uuid().optional().nullable(),
  inputData: z.any().optional(),
  responseContract: z.string().optional(),
  status: z.enum(["created", "processing", "responded"]).optional(),
  responseStatusCode: z.number().optional(),
  responseMetadata: z.any().optional(),
});

// POST /teams/:teamId/requests
requestsRouter.post("/", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    const body = requestSchema.parse(req.body);

    let finalTeamTaskId = body.teamTaskId;

    // If both teamTaskId and projectIssueId are missing, we automatically create a team task
    if (!body.teamTaskId && !body.projectIssueId) {
      // Find the target agent to assign it to
      const agent = await db.query.agents.findFirst({
        where: eq(agents.id, body.targetAgentId),
      });

      if (!agent) {
        return res.status(404).json({ error: "Target agent not found." });
      }

      const description = `### Request\n\n**Input Data:**\n\`\`\`json\n${JSON.stringify(body.inputData || {}, null, 2)}\n\`\`\`\n\n**Contract:**\n${body.responseContract || "No contract provided."}`;

      const [newTask] = await db
        .insert(teamTasks)
        .values({
          teamId,
          title: "Agent Request Task",
          descriptionMarkdown: description,
          status: 1, // To Do
          assignedToId: body.targetAgentId,
        })
        .returning();

      finalTeamTaskId = newTask.id;

      // Log task created
      await logActivity(
        teamId,
        body.requesterId,
        body.requesterType,
        "task_created",
        "task",
        newTask.id,
        { autoGeneratedFromRequest: true }
      );
    }

    const [newRequest] = await db
      .insert(teamRequests)
      .values({
        teamId,
        requesterId: body.requesterId,
        requesterType: body.requesterType,
        targetAgentId: body.targetAgentId,
        teamTaskId: finalTeamTaskId,
        projectIssueId: body.projectIssueId,
        inputData: body.inputData,
        responseContract: body.responseContract,
        status: "created",
      })
      .returning();

    // Log request created
    await logActivity(
      teamId,
      body.requesterId,
      body.requesterType,
      "request_created",
      "request",
      newRequest.id,
      { targetAgentId: body.targetAgentId }
    );

    res.status(201).json({ data: newRequest });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});

// PATCH /teams/:teamId/requests/:requestId
requestsRouter.patch("/:requestId", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    const requestId = String(req.params.requestId);
    const body = requestSchema.partial().parse(req.body);
    
    // Use unified actor context for logging
    const actorId = req.actor!.id;
    const actorType = req.actor!.type;

    if (!actorId) {
       return res.status(400).json({ error: "Actor ID is required for logging." });
    }

    const [updatedRequest] = await db
      .update(teamRequests)
      .set({
        ...body,
        updatedAt: new Date(),
      })
      .where(eq(teamRequests.id, requestId))
      .returning();

    if (!updatedRequest) {
      return res.status(404).json({ error: "Request not found." });
    }

    if (body.status === "processing") {
      await logActivity(teamId, actorId, actorType, "request_received", "request", updatedRequest.id);
    } else if (body.status === "responded") {
      await logActivity(teamId, actorId, actorType, "request_responded", "request", updatedRequest.id, {
        statusCode: updatedRequest.responseStatusCode
      });
    }

    res.json({ data: updatedRequest });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});
