import { Router } from "express";
import { db } from "../db/client";
import { teamRequests, tasks, agents, workspaces, teams, taskTypes } from "../db/schema";
import { eq, and, sql } from "drizzle-orm";
import { authMiddleware } from "../middleware/authMiddleware";
import { z } from "zod";
import { logActivity } from "../lib/activity-logger";

export const requestsRouter = Router({ mergeParams: true });

const requestSchema = z.object({
  title: z.string(),
  requesterId: z.string().uuid(),
  requesterType: z.enum(["human", "agent"]),
  targetAgentId: z.string().uuid(),
  taskId: z.string().uuid().optional().nullable(),
  inputData: z.any().optional(),
  responseContract: z.string().optional(),
  status: z.enum(["created", "processing", "responded"]).optional(),
  responseStatusCode: z.coerce.number().optional(),
  responseMetadata: z.any().optional(),
});

// POST /teams/:teamId/requests
requestsRouter.post("/", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    const body = requestSchema.parse(req.body);

    let finalTaskId = body.taskId;

    // If taskId is missing, we automatically create a task
    if (!body.taskId) {
      // Find the target agent to assign it to
      const agent = await db.query.agents.findFirst({
        where: eq(agents.id, body.targetAgentId),
      });

      if (!agent) {
        return res.status(404).json({ error: "Target agent not found." });
      }

      const description = `### Request\n\n**Input Data:**\n\`\`\`json\n${JSON.stringify(body.inputData || {}, null, 2)}\n\`\`\`\n\n**Contract:**\n${body.responseContract || "No contract provided."}`;

      const newTask = await db.transaction(async (tx) => {
        const [team] = await tx.select({ identifierPrefix: teams.identifierPrefix }).from(teams).where(eq(teams.id, teamId));
        if (!team) throw new Error("Team not found");

        let taskTypeId;
        const [defaultType] = await tx.select().from(taskTypes).where(and(eq(taskTypes.teamId, teamId), eq(taskTypes.isDefault, true))).limit(1);
        if (defaultType) taskTypeId = defaultType.id;

        const nextNumResult = await tx.execute(sql`
          SELECT COALESCE(MAX(number), 0) + 1 as next_number FROM ${tasks} WHERE team_id = ${teamId}
        `);
        const nextNumber = Number((nextNumResult.rows[0] as any).next_number);
        const identifier = `${team.identifierPrefix}-${nextNumber}`;

        const [created] = await tx
          .insert(tasks)
          .values({
            teamId,
            title: "Agent Request Task",
            descriptionMarkdown: description,
            status: 1, // To Do
            assignedToId: body.targetAgentId,
            number: nextNumber,
            identifier,
            taskTypeId,
          })
          .returning();
        return created;
      });

      finalTaskId = newTask.id;

      // Log task created
      await logActivity(
        teamId,
        body.requesterId,
        body.requesterType,
        "task_created",
        "task",
        newTask.id,
        { autoGeneratedFromRequest: true }
      );
    }

    const [newRequest] = await db
      .insert(teamRequests)
      .values({
        teamId,
        title: body.title,
        requesterId: body.requesterId,
        requesterType: body.requesterType,
        targetAgentId: body.targetAgentId,
        taskId: finalTaskId,
        inputData: body.inputData,
        responseContract: body.responseContract,
        status: "created",
      })
      .returning();

    // Log request created
    await logActivity(
      teamId,
      body.requesterId,
      body.requesterType,
      "request_created",
      "request",
      newRequest.id,
      { targetAgentId: body.targetAgentId }
    );

    res.status(201).json({ data: newRequest });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});

// GET /teams/:teamId/requests
requestsRouter.get("/", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    let statusFilter = req.query.status as string | undefined;
    let targetAgentIdFilter = req.query.targetAgentId as string | undefined;

    const conditions: any[] = [eq(teamRequests.teamId, teamId)];
    if (statusFilter) {
      conditions.push(eq(teamRequests.status, statusFilter as "created" | "processing" | "responded"));
    }
    if (targetAgentIdFilter) {
      conditions.push(eq(teamRequests.targetAgentId, targetAgentIdFilter));
    }

    const rows = await db.query.teamRequests.findMany({
      where: and(...conditions),
      orderBy: (teamRequests, { desc }) => [desc(teamRequests.createdAt)],
    });

    res.json({ data: rows });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});

// GET /teams/:teamId/requests/:requestId
requestsRouter.get("/:requestId", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    const requestId = String(req.params.requestId);

    const [request] = await db
      .select()
      .from(teamRequests)
      .where(and(eq(teamRequests.id, requestId), eq(teamRequests.teamId, teamId)));

    if (!request) {
      return res.status(404).json({ error: "Request not found." });
    }

    res.json({ data: request });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});

// PATCH /teams/:teamId/requests/:requestId
requestsRouter.patch("/:requestId", authMiddleware, async (req, res) => {
  try {
    const teamId = String(req.params.teamId);
    const requestId = String(req.params.requestId);
    const body = requestSchema.partial().parse(req.body);
    
    // Use unified actor context for logging
    const actorId = req.actor!.id;
    const actorType = req.actor!.type;

    if (!actorId) {
       return res.status(400).json({ error: "Actor ID is required for logging." });
    }

    const [updatedRequest] = await db
      .update(teamRequests)
      .set({
        ...body,
        updatedAt: new Date(),
      })
      .where(eq(teamRequests.id, requestId))
      .returning();

    if (!updatedRequest) {
      return res.status(404).json({ error: "Request not found." });
    }

    if (body.status === "processing") {
      await logActivity(teamId, actorId, actorType, "request_received", "request", updatedRequest.id);
    } else if (body.status === "responded") {
      await logActivity(teamId, actorId, actorType, "request_responded", "request", updatedRequest.id, {
        statusCode: updatedRequest.responseStatusCode
      });
    }

    res.json({ data: updatedRequest });
  } catch (err: any) {
    res.status(400).json({ error: err.message || "Invalid input" });
  }
});
